name: Build QMK

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  build_the_firmware:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set release tag
        run: |
          echo "TAG=`date --rfc-3339=date`" >> $GITHUB_ENV

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install QMK
        run: |
          echo "QMK_HOME=${HOME}/qmk_firmware" >> $GITHUB_ENV
          pip install --user qmk
          qmk setup -y
      
      - name: Setup keyboards
        run: |
          rm -rd $QMK_HOME/keyboards/*
          cp -r $GITHUB_WORKSPACE/* $QMK_HOME/keyboards/.

      - name: Qmk Lint
        run: |
          qmk lint -kb 3w6
          qmk lint -kb charybdis_nano/elitec

      - name: Build 3w6
        run: qmk compile -kb 3w6 -km default

      - name: Build charybdis_nano
        run: qmk compile -kb charybdis_nano/elitec -km default 
          
      - name: Build cornerp
        run: qmk compile -kb cornerp -km default

      - name: Build dasbob
        run: qmk compile -kb dasbob -km halmak

      - name: Build sofle
        run: qmk compile -kb sofle -km rgb_with_ind_halmak 
      
      - name: Get git short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TAG }}-${{ env.SHORT_SHA }}
          path: |
            ${{ env.QMK_HOME }}/.build/*.hex
            ${{ env.QMK_HOME }}/.build/*.bin
            ${{ env.QMK_HOME }}/.build/*.uf2
