name: Build QMK

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set release tag
        run: |
          echo "TAG=`date --rfc-3339=date`" >> $GITHUB_ENV

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install QMK
        run: |
          echo "QMK_HOME=${HOME}/qmk_firmware" >> $GITHUB_ENV
          pip install --user qmk
          qmk setup -y
      
      - name: Setup keyboards
        run: |
          rm -rd $QMK_HOME/keyboards/*
          cp -r $GITHUB_WORKSPACE/* $QMK_HOME/keyboards/.

      - name: Build 3w6
        run: |
          ls $QMK_HOME/keyboards/3w6
          qmk compile -kb 3w6 -km halmak_pimoroni
          ls $QMK_HOME/.build

      - name: Build charybdis_nano
        run: |
          ls $QMK_HOME/keyboards/charybdis_nano
          qmk compile -kb charybdis_nano -mk halmak
          ls $QMK_HOME/.build
          
      - name: Build cornerp
        run: |
          ls $QMK_HOME/keyboards/cornerp
          qmk compile -kb cornerp -km default
          ls $QMK_HOME/.build

      - name: Build dasbob
        run: |
          ls $QMK_HOME/keyboards/dasbob
          qmk compile -kb dasbob -km halmak
          ls $QMK_HOME/.build

      - name: Build sofle
        run: |
          ls $QMK_HOME/keyboards/sofle
          qmk compile -kb sofle -km rgb_with_ind_halmak 
          ls $QMK_HOME/.build
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: |
            $QMK_HOME/.build/*.hex
            $QMK_HOME/.build/*.bin
            $QMK_HOME/.build/*.uf2
